<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>RimworldArmWrestling</AssemblyName>
    <RootNamespace>RimworldArmWrestling</RootNamespace>
    <Nullable>disable</Nullable>
    <OutputPath>../Assemblies/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup>
    <RimWorldPath>/Users/goldzar/Library/Application Support/Steam/steamapps/common/RimWorld/RimWorldMac.app</RimWorldPath>
    <ManagedPath>$(RimWorldPath)/Contents/Resources/Data/Managed</ManagedPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedPath)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedPath)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
